### ISSUE TITLE
General Failure InsertionFaulted?

### ISSUE THREAD

**Issue by Mitsunee** [rayshift/rayshift#3]
Just tried to put my JP friend ID and got this error
id: 044038865 (`044,038,865` <- inserted in textbox like this, tho according to the url that got converted properly)
time: around 3:15am GMT+1 (aka few minutes before I posted this issue)

Edit:
The page seems to now be looping this message:
![Screenshot_20200325_031818](https://user-images.githubusercontent.com/19474909/77494907-65ed3800-6e47-11ea-8f3b-a4c704d71415.png)

**Comment by neobenedict** [comment]
Can you take a picture of your two support decks (or one, if you only have one) in-game? Will help speed this up, dealing with a lot of issues atm

**Comment by Mitsunee** [comment]
here's my setup, sorry for the slow response, was farming a bit~
![Screenshot_2020-03-25-04-35-04](https://user-images.githubusercontent.com/19474909/77499338-1fe9a180-6e52-11ea-989d-f891ed120871.png)
![Screenshot_2020-03-25-04-35-08](https://user-images.githubusercontent.com/19474909/77499344-22e49200-6e52-11ea-92a3-8da62d6141ce.png)

As an hour has passed I just tried to load my profile again and got the same error as described above.

**Comment by neobenedict** [comment]
Thanks, I won't be able to fix this until the maintenance is over but I have identified the issue.

**Comment by neobenedict** [comment]
Should be fixed, thanks.

**Comment by Mitsunee** [comment]
Yep, works perfectly now, thx a lot for the quick fix~
