### ISSUE TITLE
The final mordred art of the Apocrypha event does not appear in the friend ID

### ISSUE THREAD

**Issue by MerlinMagus** [rayshift/rayshift#5]
![bandicam 2020-04-08 18-36-34-737](https://user-images.githubusercontent.com/63363402/78843250-e8d5cd00-79c7-11ea-8f89-2577ff7a398f.jpg)

 
This is how it appears to me, I also tried to find other supports of some friends with mordred and it did not look either.

I imagine they haven't updated it yet, but would I still like to know by when would they have that ready?

**Comment by neobenedict** [comment]
Fixed
