### ISSUE TITLE
rayshift.io unable to find friend lookup

### ISSUE THREAD

**Issue by SilentOfChaos** [rayshift/rayshift#7]
![image](https://user-images.githubusercontent.com/77503363/131832832-7eca2e1b-3687-48af-b880-aab9ef136f4b.png)
Friend ID Lookup -> 244,403,357 Search NA -> Gives out error message as shown in the image
Error Message: Request ID: 00-e06fc66e09a9744f8382ff2566da7be9-ff1cec27a5983c4f-00

**Comment by neobenedict** [comment]
fixed
